<div>
	<form id="options_form" action="" method="post">
		<div>
			<select name="option">
				<option value="name">имя</option>
				<option value="password">пароль</option>
				<option value="notifications">уведомления</option>
			</select>
		</div>
		<div>
			<input type="text" name="value">
		</div>
        <div>
            <select name="confirmationMethod">
                <option value="file">file</option>
            </select>
        </div>
		<div>
			<button type="submit">Изменить</button>
		</div>
	</form>
</div>

<script>

let formEl = document.getElementById('options_form');
formEl.addEventListener('submit', function (ev) {
    ev.preventDefault();

    fetch(ev.target.action, {
        method: ev.target.method,
        body: new URLSearchParams(new FormData(ev.target)),
    }).then(function (response) {
        ev.target.reset();
        if (! response.ok) {
            alert('Error: ' + response.text());
        }

        alert(response.text());
    }, function () {
        alert('Error')
    });
});

</script>