<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="/assets/app.css">
</head>
<body>
    <div>
        <form action="/auth" data-method="put" id="login_form">
            <div>
                <label>Логин <input type="text" name="login"></label>
            </div>
            <div>
                <label>Пароль <input type="password" name="password"></label>
            </div>
            <div>
                <button type="submit">Войти</button>
            </div>
        </form>
    </div>

    <script>

        let formEl = document.getElementById('login_form');
        formEl.addEventListener('submit', function (ev) {
            ev.preventDefault();

            fetch(ev.target.action, {
                method: ev.target.dataset.method,
                body: new URLSearchParams(new FormData(ev.target)),
            }).then(function (response) {
                response.text().then(function (text) {
                    if (!response.ok) {
                        alert('Error: ' + text);

                        return;
                    }

                    location.href = 'confirmations/form';
                });
            }, function () {
                alert('Error')
            });
        });

    </script>
</body>
</html>
